Repository vmware-labs/wasm-workers-server, pull requests merged in 2022-11, with the labels that each got.

#16 feat: Bump Wasmtime and Anyhow versions
  Cargo.lock
  Cargo.toml
Labels: cla-not-required

#22 feat: run fmt and clippy in the CI
  .github/workflows/build.yml
  src/main.rs
  src/router.rs
  src/runner.rs
Labels: ⚙️ automation, cla-not-required

#23 feat: add new workflow to cross-compile wws
  .github/workflows/artifacts.yml
Labels: cla-not-required

#27 feat: upgrade wasmtime to 2.0.2
  Cargo.lock
  Cargo.toml
Labels: 🚀 enhancement, cla-not-required

#29 feat: read static files from the public folder
  Cargo.lock
  Cargo.toml
  docs/docs/containers.md
  docs/docs/features/key-value.md
  docs/docs/features/static-assets.md
  src/main.rs
Labels: cla-not-required

#33 Remove Arc<RwLock> when initializing arguments
  src/main.rs
Labels: cla-not-required

#32 fix: normalize API routes using Rust path entities
  .github/workflows/build.yml
  src/router.rs
Labels: ⚠️ bug, cla-not-required

#37 feat: add the prefix option to prepend a path to all URLs
  src/main.rs
  src/router.rs
Labels: 🚀 enhancement, cla-not-required

#38 fix: avoid service JS files inside public folder as worker
  src/router.rs
Labels: ⚠️ bug, cla-not-required

#40 feat: bump Wasmtime version to 3.0.0
  Cargo.lock
  Cargo.toml
Labels: cla-not-required, ⬆️ updates

#41 chore: bump multiple dependency versions with cargo update
  Cargo.lock
Labels: cla-not-required, ⬆️ updates

#42 feat: configure and inject environment variables in workers
  docs/docs/features/environment-variables.md
  docs/docs/tutorials/javascript-workers.md
  docs/docs/tutorials/rust-workers.md
  examples/js-json/handler.js
  examples/js-json/handler.toml
  examples/rust-basic/basic.toml
  examples/rust-basic/src/main.rs
  kits/javascript/src/main.rs
  kits/javascript/wasm-workers-quick-js-engine.wasm
  src/config.rs
  src/main.rs
  src/runner.rs
Labels: 🚀 enhancement, cla-not-required

#45 feat: allow returning an array of bytes from Rust workers
  Cargo.lock
  Cargo.toml
  docs/docs/tutorials/rust-workers.md
  examples/pdf-create/Cargo.lock
  examples/pdf-create/Cargo.toml
  examples/pdf-create/src/main.rs
  examples/rust-basic/Cargo.lock
  examples/rust-basic/src/main.rs
  examples/rust-kv/src/main.rs
  kits/javascript/src/glue.js
  kits/javascript/wasm-workers-quick-js-engine.wasm
  kits/rust/Cargo.toml
  kits/rust/handler/src/expand.rs
  kits/rust/src/content.rs
  kits/rust/src/io.rs
  kits/rust/src/lib.rs
  src/data/kv.rs
  src/main.rs
  src/runner.rs
Labels: 🚀 enhancement, cla-not-required, 🚨 breaking change

#48 feat: rename attr macro handler to worker
  Cargo.lock
  Cargo.toml
  README.md
  docs/docs/containers.md
  docs/docs/how-it-works.md
  docs/docs/start.md
  docs/docs/tutorials/javascript-workers.md
  docs/docs/tutorials/rust-workers.md
  docs/src/components/HomepageFeatures/index.js
  examples/README.md
  examples/pdf-create/src/main.rs
  examples/rust-basic/Cargo.lock
  examples/rust-basic/src/main.rs
  examples/rust-kv/Cargo.lock
  examples/rust-kv/kv.toml
  examples/rust-kv/src/main.rs
  kits/javascript/README.md
  kits/rust/Cargo.toml
  kits/rust/src/io.rs
  kits/rust/src/lib.rs
  kits/rust/worker/Cargo.toml
  kits/rust/worker/src/args.rs
  kits/rust/worker/src/expand.rs
  kits/rust/worker/src/lib.rs
  src/config.rs
  src/data/README.md
  src/data/kv.rs
  src/main.rs
  src/router.rs
  src/runner.rs
Labels: 🚀 enhancement, cla-not-required, 🚨 breaking change

#51 fix: make vars section optional in the configuration
  src/config.rs
Labels: 🐛 bug, cla-not-required

#52 feat: automate container build with GitHub Actions
  .github/workflows/artifacts.yml
  .github/workflows/container-preview.yml
  .github/workflows/container-release.yml
  image/Prebuilt.dockerfile
Labels: 🚀 enhancement, cla-not-required
