Repository vmware-labs/wasm-workers-server, pull requests merged in 2023-07, with the labels that each got.

#168 feat: add the HTTP bindings to perform HTTP requests from workers
  Cargo.lock
  Cargo.toml
  crates/project/Cargo.toml
  crates/worker/Cargo.toml
  crates/worker/src/bindings/http.rs
  crates/worker/src/bindings/mod.rs
  crates/worker/src/lib.rs
  deny.toml
  wit/core/http-types.wit
  wit/core/http.wit
Labels: 🚀 enhancement, cla-not-required

#172 doc: Fixing minor typos in documentation.
  docs/docs/get-started/quickstart.md
  docs/docs/languages/javascript.md
Labels: :memo: documentation, cla-not-required

#169 feat: add the fetch and more APIs to the JavaScript kit
  Cargo.lock
  examples/js-fetch/README.md
  examples/js-fetch/index.js
  kits/javascript/.gitignore
  kits/javascript/Cargo.toml
  kits/javascript/build.rs
  kits/javascript/shims/bindings.js
  kits/javascript/shims/index.js
  kits/javascript/shims/package.json
  kits/javascript/shims/types/cache.js
  kits/javascript/shims/types/headers.js
  kits/javascript/shims/types/index.js
  kits/javascript/shims/types/request.js
  kits/javascript/shims/types/response.js
  kits/javascript/src/bindings.rs
  kits/javascript/src/error.rs
  kits/javascript/src/glue.js
  kits/javascript/src/main.rs
  kits/javascript/wasm-workers-quick-js-engine.wasm
Labels: 🚀 enhancement, cla-not-required

#173 feat: add new Go bindings to perform HTTP requests
  docs/docs/languages/go.md
  examples/go-basic/go.mod
  examples/go-basic/go.sum
  examples/go-fetch/README.md
  examples/go-fetch/go.mod
  examples/go-fetch/go.sum
  examples/go-fetch/main.go
  kits/go/worker/README.md
  kits/go/worker/bindings/bindings.c
  kits/go/worker/bindings/bindings.go
  kits/go/worker/bindings/bindings.h
  kits/go/worker/bindings/bindings_component_type.o
  kits/go/worker/bindings/bindings_types.go
  kits/go/worker/worker.go
  wit/go-ephemeral/http-types.wit
  wit/go-ephemeral/http.wit
Labels: 🚀 enhancement, cla-not-required

#174 feat: allow configuring the http_requests via TOML
  crates/api-manage/src/models/worker_config.rs
  crates/worker/src/bindings/http.rs
  crates/worker/src/config.rs
  crates/worker/src/features/data.rs
  crates/worker/src/features/folders.rs
  crates/worker/src/features/http_requests.rs
  crates/worker/src/features/mod.rs
  crates/worker/src/lib.rs
  examples/go-fetch/index.toml
  examples/js-fetch/index.toml
  examples/rust-fetch/index.toml
Labels: 🚀 enhancement, cla-not-required

#180 docs: add the HTTP request documentation. Improve features' docs
  docs/docs/features/_category_.json
  docs/docs/features/all.md
  docs/docs/features/dynamic-routes.md
  docs/docs/features/environment-variables.md
  docs/docs/features/http-requests.md
  docs/docs/features/key-value.md
  docs/docs/features/mount-folders.md
  docs/docs/features/static-assets.md
  docs/docs/languages/go.md
  docs/docs/languages/javascript.md
  docs/docs/languages/python.md
  docs/docs/languages/ruby.md
  docs/docs/languages/rust.md
Labels: :memo: documentation, cla-not-required

#184 chore: bump rust to 1.71.0 and use vendored openssl
  image/Dockerfile
Labels: cla-not-required

#190 docs: add example and docs about using Python libraries in a project
  docs/docs/languages/python.md
  examples/python-libs/.wws.toml
  examples/python-libs/README.md
  examples/python-libs/_libs/.gitignore
  examples/python-libs/index.py
  examples/python-libs/index.toml
  examples/python-libs/requirements.txt
Labels: :memo: documentation, cla-not-required, 🔨 sdks

#181 feat: add lib.rs with gated child crates
  Cargo.toml
  src/lib.rs
Labels: cla-not-required

#186 chore: place wws under /opt/wws and keep /app in prebuilt images too
  image/Prebuilt.dockerfile
Labels: cla-not-required
