Repository vmware-labs/wasm-workers-server, pull requests merged in 2023-10, with the labels that each got.

#228 chore: avoid using format when building asset paths and double-check path
  crates/server/src/handlers/assets.rs
Labels: 🚀 enhancement, cla-not-required

#231 chore: register wasi-nn on the linker
  crates/runtimes/src/errors.rs
  crates/runtimes/src/modules/external.rs
  crates/worker/src/lib.rs
Labels: cla-not-required

#229 feat: manage static assets properly in Unix and Windows
  crates/server/src/handlers/assets.rs
  examples/js-json/public/robots.txt
  examples/js-params/public/main.css
  tests/data/public/about/index.html
  tests/data/public/index.html
  tests/data/public/main.css
  tests/e2e.rs
Labels: 🚀 enhancement, cla-not-required

#241 chore: update `wws --help` output on the main documentation page
  docs/src/pages/index.js
Labels: :memo: documentation, cla-not-required

#244 update: bump rustix to fix a security issue
  Cargo.lock
Labels: cla-not-required, ⬆️ updates
