Repository vmware-labs/wasm-workers-server, pull requests merged in 2023-08, with the labels that each got.

#195 fix rust language example
  docs/docs/languages/rust.md
Labels: :memo: documentation

#201 feat: add WASI-NN bindings to Wasm Workers Server
  Cargo.lock
  Cargo.toml
  crates/worker/Cargo.toml
  crates/worker/src/config.rs
  crates/worker/src/features/mod.rs
  crates/worker/src/features/wasi_nn.rs
  crates/worker/src/lib.rs
  docs/docs/features/dynamic-routes.md
  docs/docs/features/http-requests.md
  docs/docs/features/machine-learning.md
  docs/docs/features/mount-folders.md
  docs/docs/features/multiple-language-runtimes.md
  docs/docs/features/static-assets.md
  docs/static/img/docs/features/wasi-nn.webp
  examples/Makefile
  examples/rust-wasi-nn/.gitignore
  examples/rust-wasi-nn/Cargo.lock
  examples/rust-wasi-nn/Cargo.toml
  examples/rust-wasi-nn/README.md
  examples/rust-wasi-nn/_images/.gitkeep
  examples/rust-wasi-nn/_models/dataset.json
  examples/rust-wasi-nn/index.js
  examples/rust-wasi-nn/inference.toml
  examples/rust-wasi-nn/prepare.sh
  examples/rust-wasi-nn/public/main.css
  examples/rust-wasi-nn/public/main.js
  examples/rust-wasi-nn/src/main.rs
Labels: 🚀 enhancement, cla-not-required

#203 chore: remove stderr path
  crates/server/src/handlers/worker.rs
  crates/server/src/lib.rs
  crates/worker/src/lib.rs
  crates/worker/src/stdio.rs
  src/main.rs
Labels: cla-not-required
