Repository vmware-labs/wasm-workers-server, pull requests merged in 2023-09, with the labels that each got.

#196 add Zig support #144
  .gitignore
  README.md
  docs/docs/features/all.md
  docs/docs/features/dynamic-routes.md
  docs/docs/features/environment-variables.md
  docs/docs/features/http-requests.md
  docs/docs/features/key-value.md
  docs/docs/features/mount-folders.md
  docs/docs/languages/zig.md
  docs/src/css/custom.css
  docs/static/img/languages/zig.svg
  examples/README.md
  examples/zig-basic/README.md
  examples/zig-basic/build.zig
  examples/zig-basic/src/basic.zig
  examples/zig-kv/README.md
  examples/zig-kv/build.zig
  examples/zig-kv/src/worker-kv.zig
  examples/zig-kv/zig-out/bin/worker-kv.toml
  examples/zig-params/README.md
  examples/zig-params/build.zig
  examples/zig-params/src/worker-params.zig
  kits/zig/worker/README.md
  kits/zig/worker/src/worker.zig
Labels: 🚀 enhancement, 🔨 sdks

#197 feat: add catch all routes
  crates/router/src/lib.rs
  crates/router/src/route.rs
  crates/router/src/route/route_type.rs
  crates/router/src/route/segment.rs
  tests/data/params/[id]/sub.wasm
  tests/data/params/sub/[...all].wasm
  tests/data/params/sub/sub/[...all].wasm
Labels: 🚀 enhancement

#214 Document catch all routes
  docs/docs/features/all.md
  docs/docs/features/dynamic-routes.md
  docs/docs/features/environment-variables.md
  docs/docs/features/http-requests.md
  docs/docs/features/key-value.md
  docs/docs/features/machine-learning.md
  docs/docs/features/mount-folders.md
  examples/js-catchall/README.md
  examples/js-catchall/[...slug]/index.js
  examples/js-catchall/about.js
  examples/js-catchall/other/[...slug].js
Labels: cla-not-required

#217 feat: add Zig mount example
  docs/docs/languages/zig.md
  examples/zig-mount/build.zig
  examples/zig-mount/src/mount.zig
  examples/zig-mount/zig-out/bin/_images/zig.svg
  examples/zig-mount/zig-out/bin/mount.toml
  kits/zig/worker/src/worker.zig
Labels: cla-not-required

#216 feat: add Zig environment variables example
  docs/docs/features/environment-variables.md
  docs/docs/languages/zig.md
  examples/zig-envs/README.md
  examples/zig-envs/build.zig
  examples/zig-envs/src/envs.zig
  examples/zig-envs/zig-out/bin/envs.toml
Labels: cla-not-required

#219 chore: bump wasmtime to 10.0.2
  Cargo.lock
  Cargo.toml
Labels: cla-not-required

#221 bump: upgrade wasmtime and related dependencies to 13.0.0
  Cargo.lock
  Cargo.toml
  crates/runtimes/src/modules/external.rs
  crates/runtimes/src/modules/javascript.rs
  crates/runtimes/src/runtime.rs
  crates/worker/Cargo.toml
  crates/worker/src/lib.rs
  crates/worker/src/stdio.rs
Labels: cla-not-required, ⬆️ updates

#224 feat: allow to preload ML models when running inference
  Cargo.toml
  crates/worker/src/features/wasi_nn.rs
  crates/worker/src/lib.rs
  examples/Makefile
  examples/rust-wasi-nn-preload/.gitignore
  examples/rust-wasi-nn-preload/Cargo.lock
  examples/rust-wasi-nn-preload/Cargo.toml
  examples/rust-wasi-nn-preload/README.md
  examples/rust-wasi-nn-preload/_data/dataset.json
  examples/rust-wasi-nn-preload/_images/.gitkeep
  examples/rust-wasi-nn-preload/_models/mobilenet/.gitkeep
  examples/rust-wasi-nn-preload/index.js
  examples/rust-wasi-nn-preload/inference.toml
  examples/rust-wasi-nn-preload/inference.wasm
  examples/rust-wasi-nn-preload/prepare.sh
  examples/rust-wasi-nn-preload/public/main.css
  examples/rust-wasi-nn-preload/public/main.js
  examples/rust-wasi-nn-preload/src/main.rs
Labels: 🚀 enhancement, cla-not-required
