Repository vmware-labs/wasm-workers-server, pull requests merged in 2023-05, with the labels that each got.

#123 update: bump h2, reqwest and wasmtime
  Cargo.lock
  Cargo.toml
Labels: cla-not-required, ⬆️ updates

#127 feat: allow configuring stderr when running the server
  crates/server/src/handlers/worker.rs
  crates/server/src/lib.rs
  crates/worker/src/lib.rs
  crates/worker/src/stdio.rs
  src/main.rs
Labels: 🚀 enhancement, cla-not-required

#128 python worker: fix broken link
  docs/docs/languages/python.md
Labels: :memo: documentation

#136 fix: use open_ambient_dir instead of fs::File::open to load folders
  crates/runtimes/src/modules/external.rs
  crates/runtimes/src/modules/javascript.rs
  crates/worker/src/lib.rs
Labels: 🐛 bug, cla-not-required

#140 feat: add cargo deny initial configuration and run it in the CI
  .github/workflows/build.yml
  Cargo.lock
  deny.toml
Labels: 🚀 enhancement, cla-not-required

#141 Added error message and exposes WASM error message
  crates/server/src/handlers/worker.rs
Labels: 🚀 enhancement

#129 Add support for Go
  README.md
  docs/docs/features/dynamic-routes.md
  docs/docs/features/environment-variables.md
  docs/docs/features/key-value.md
  docs/docs/get-started/quickstart.md
  docs/docs/languages/go.md
  docs/src/components/HomepageFeatures/index.js
  docs/src/css/custom.css
  docs/static/img/languages/go.svg
  examples/go-basic/main.go
  examples/go-envs/envs.go
  examples/go-envs/envs.toml
  examples/go-kv/counter.go
  examples/go-kv/counter.toml
  examples/go-params/main.go
  examples/go-params/public/main.css
  examples/go-params/public/water.min.css
  go.mod
  go.sum
  kits/go/worker/doc.go
  kits/go/worker/worker.go
Labels: 🚀 enhancement

#146 fix: set a global timeout per e2e test and check for the command output
  .github/workflows/build.yml
  tests/e2e.rs
Labels: 🐛 bug, cla-not-required

#148 fix: add missing certs to the wws container
  image/Prebuilt.dockerfile
Labels: 🐛 bug, cla-not-required
